
spring:
  profiles:
    active: dev

mybatis:
  mapperLocations: classpath:mapper/*.xml

---


spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
---

spring:
    mvc:
      view:
        prefix: /templates/
        suffix: .html
      static-path-pattern: /static/**
server:
  port: 8080


